_BASE_: "../../../configs/Base-CenterNet.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  CENTERNET:
    NUM_CLASSES: 1
INPUT:
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TRAIN: (320, 480, 512,)
  CROP:
    ENABLED: False
    SIZE: [0.8, 0.8]
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
DATASETS:
  TRAIN: ("ccpd_rotate_train",)
  TEST: ("ccpd_rotate_train",)
SOLVER:
  IMS_PER_BATCH: 4
  STEPS: (200000, 230000)
  MAX_ITER: 250000
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000
VIS_PERIOD: 100
OUTPUT_DIR: '/media/ps/A1/XPC/data/CCPD/ccpd_rotate_coco/output_centernet'