_BASE_: "../Base-RetinaFace.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_fpn_wo_top_block_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
    NORM: "BN"
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
DATASETS:
  TRAIN: ("ccpd_rotate_train",)
  TEST: ("ccpd_rotate_train",)
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (200000, 230000)
  MAX_ITER: 250000
OUTPUT_DIR: '/media/ps/A/XPC/data/CCPD/ccpd_rotate_coco/output'